name: userformpages
---
SubmittedForm:
  extensions:
    - SubmittedFormListingExtension
SubmittedFormField:
  extensions:
    - SubmittedFormFieldListingExtension
EditableFormField:
  extensions:
    - EditableFormFieldListingExtension
---
Only:
  classexists: 'SolrSearch'
---
UserSubmissionPage:
  extensions:
    - UserSubmissionSolrExtension